In [1]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "Prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

# 2D Array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64 (6,)
['1' '2' '3' '4' '5' 'Prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [ ]:
# Creating array from scratch

arr1 = np.zeros((3,4), dtype="int64") # prefill with 0
print(arr1, arr1.shape)

arr2 = np.ones((2,3)) # prefill with 1
print(arr2, arr2.shape)

arr3 = np.full((2,3), 100) # prefill with a particular value
print(arr3, arr3.shape)

arr4 = np.eye(3) # identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) # range function
print(arr5, arr5.shape)

arr6 = np.linspace(0, 110, 10) # evenly spaced array
print(arr6, arr6.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  0.          12.22222222  24.44444444  36.66666667  48.88888889
  61.11111111  73.33333333  85.55555556  97.77777778 110.        ] (10,)


In [ ]:
# Difference between execution performance of python list & numpy array

import time
size = 1_000_000

py_list = list(range(size))
start = time.time()
sq_list = [x ** 2 for x in py_list]
end = time.time()
print(f"Python list time in seconds = {end - start}")

np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr ** 2
end = time.time()
print(f"NumPy array time in seconds = {end - start}")

Python list time in seconds = 0.20905661582946777
NumPy array time in seconds = 0.003573179244995117


In [ ]:
# Difference between them in terms of memory

import sys
print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy array size = {np_arr.nbytes} bytes")

Python list size = 8000056000000 bytes
Numpy array size = 8000000 bytes


In [ ]:
# Properties of Array

arr = np.array([[1,2,3], [4,5,6],[7,8,9]])

print(arr, arr.shape) # Dimension of array

print(arr.size) # Total elements of array

print(arr.dtype) # Datatype of array

print(arr.ndim) # No. of dimensions

# TypeCasting
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype, float_arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64 2


In [ ]:
# Operations in Array

# Reshaping an array
arr = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print(arr, arr.shape)
reshaped = arr.reshape(3,4)
print(reshaped, reshaped.shape)

# Flattening an array
flattened = arr.flatten()
print(flattened, flattened.shape)

# Indexing
print(arr[0][1])
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1[4])

# Fancy Indexing
idx = [1,4,2]
print(arr1[idx])

# Boolean Indexing
print(arr1[arr1 > 2])
print(arr1[arr1 % 2 == 0])

# Slicing
print(arr1[1:3])
print(arr1[:4])
print(arr1[1:])
print(arr[::2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,)
2
5
[2 5 3]
[3 4 5]
[2 4]
[2 3]
[1 2 3 4]
[2 3 4 5]
[[1 2 3]
 [7 8 9]]


In [ ]:
# Difference between slicing in Python list and numpy array

# Python List
nums = [1, 2, 3, 4, 5] # -> creates a copy of sliced index
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 123
print(sub_list)
print(nums)

# NumPy Array
arr = np.array([1, 2, 3, 4, 5]) # -> creates a view of the array as sub_array with original values
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 112
print(sub_arr)
print(arr)

# Creating Copy of array 
sub_arr2 = arr[1:3].copy()
print(sub_arr)
sub_arr2[1] = 30
print(sub_arr2)
print(arr)

[2, 3]
[123, 3]
[1, 2, 3, 4, 5]
[2 3]
[112   3]
[  1 112   3   4   5]
[112   3]
[112  30]
[  1 112   3   4   5]


In [8]:
# Multi Dimensional Array
# 2D Array
arr2D = np.array([[1,2,3], [4,5,6],[6,7,8]])
print(arr2D)
print(np.sum(arr2D))

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

# Slicing in 2D array
print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [6 7 8]]
42
[ 6 15 21]
[11 14 17]
[[2]
 [5]]


In [19]:
# 3D Array
arr3D = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]], [[19,20,21], [22,23,24],[25,26,27]]])
print(arr3D, arr3D.shape)

#indexing
print(arr3D[2,1,1])

# Slicing
print(arr3D[:,0,:])

arr3D[:,0,:] = 10
print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] (3, 3, 3)
23
[[ 1  2  3]
 [10 11 12]
 [19 20 21]]
[[[10 10 10]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 10 10]
  [13 14 15]
  [16 17 18]]

 [[10 10 10]
  [22 23 24]
  [25 26 27]]]


In [22]:
# Vectorization

arr = np.array([1, 2, 3, 4, 5])

arr2 = np.array([5, 4, 6, 7, 3])

print(arr ** 2)
print(arr + arr2)

[ 1  4  9 16 25]
[ 6  6  9 11  8]


In [24]:
# Brodcasting

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(arr + arr2)
print(arr1 + 10)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
[11 12 13 14 15]


In [27]:
# Vector Normalization

arr = np.array([[1,2], [3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr - mean)/std_dev

print(normalized_arr)
print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [28]:
# Column Wise Normalization

arr = np.array([[1,2], [3,4], [5,6]])

mean = np.mean(arr, axis = 0)
std_dev = np.std(arr, axis = 0)
normalized_arr = (arr - mean)/ std_dev

print(normalized_arr)
print(mean)
print(std_dev)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
[3. 4.]
[1.63299316 1.63299316]
