In [2]:
import numpy as np

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "Prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

# 2D Array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64 (6,)
['1' '2' '3' '4' '5' 'Prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [19]:
# Creating array from scratch

arr1 = np.zeros((3,4), dtype="int64") # prefill with 0
print(arr1, arr1.shape)

arr2 = np.ones((2,3)) # prefill with 1
print(arr2, arr2.shape)

arr3 = np.full((2,3), 100) # prefill with a particular value
print(arr3, arr3.shape)

arr4 = np.eye(3) # identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) # range function
print(arr5, arr5.shape)

arr6 = np.linspace(0, 110, 10) # evenly spaced array
print(arr6, arr6.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  0.          12.22222222  24.44444444  36.66666667  48.88888889
  61.11111111  73.33333333  85.55555556  97.77777778 110.        ] (10,)


In [10]:
# Difference between execution performance of python list & numpy array

import time
size = 1_000_000

py_list = list(range(size))
start = time.time()
sq_list = [x ** 2 for x in py_list]
end = time.time()
print(f"Python list time in seconds = {end - start}")

np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr ** 2
end = time.time()
print(f"NumPy array time in seconds = {end - start}")

Python list time in seconds = 0.20905661582946777
NumPy array time in seconds = 0.003573179244995117


In [5]:
# Difference between them in terms of memory

import sys
print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy array size = {np_arr.nbytes} bytes")

Python list size = 8000056000000 bytes
Numpy array size = 8000000 bytes


In [11]:
# Properties of Array

arr = np.array([[1,2,3], [4,5,6],[7,8,9]])

print(arr, arr.shape) # Dimension of array

print(arr.size) # Total elements of array

print(arr.dtype) # Datatype of array

print(arr.ndim) # No. of dimensions

# TypeCasting
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype, float_arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64 2
